version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acoemprendedores_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - acoemprendedores_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: acoemprendedores_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: acoemprendedores
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - acoemprendedores_network
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: acoemprendedores_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - acoemprendedores_network
    depends_on:
      - app

volumes:
  dbdata:

networks:
  acoemprendedores_network:
    driver: bridge