version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped

networks:
  app-network: