apiVersion: apps/v1
kind: Deployment
metadata:
  name: acoemprendedores-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acoemprendedores-db
  template:
    metadata:
      labels:
        app: acoemprendedores-db
    spec:
      containers:
        - name: db
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret
            - name: MYSQL_DATABASE
              value: acoemprendedores
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: acoemprendedores-pvc